name: SheepMage
version: '${project.version}'
main: me.radcriminal77.sheepmage.SheepMage
api-version: 1.19
authors: [ RadCriminal77 ]
description: A plugin unlike any
depend: [ Vault ]
commands:
  SheepWand:
    description: Gives a player a sheep wand
    usage: /<command> [player]
    aliases: [ sw ]
    permission: sheepmage.sheepwand
  ReloadSheepMage:
    description: Reload SheepMage's config.yml
    usage: /<command>
    permission: sheepmage.reload
permissions:
  sheepmage.sheepwand:
    description: Allows SheepWand command
    default: op
  sheepmage.reload:
    description: Allows ReloadSheepMage command
    default: op